name: Update YouTube Live Streams

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小時執行一次
  workflow_dispatch:  # 可手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-api-python-client

      - name: Run YouTube Live Scraper
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python youtube_live_scraper.py

      - name: Commit and Push updates
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}  # 此處使用 PAT_TOKEN（請先在 Secrets 中新增）
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          # 如果 live_streams.txt 存在則提交
          if [ -f "youtube_live_streams.txt" ]; then
            git add youtube_live_streams.txt
            git commit -m "Update YouTube live streams [skip ci]" || echo "No changes to commit"
          else
            echo "youtube_live_streams.txt 不存在，跳過 commit"
          fi
          git push


- name: Commit and Push updates
  env:
    PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  run: |
    git config --global user.name "GitHub Actions"
    git config --global user.email "actions@github.com"
    git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
    # 拉取远程更改并尝试自动合并
    git pull origin main --rebase
    # 添加并提交更改
    git add youtube_live_streams.txt
    git commit -m "Update YouTube live streams [skip ci]" || echo "No changes to commit"
    # 推送更改
    git push origin main
