name: Update YouTube Live Streams

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小時執行一次
  workflow_dispatch:  # 可手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install google-api-python-client

      - name: Run YouTube Live Scraper
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python youtube_live_scraper.py

      - name: Commit and Push updates
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 設定遠端 URL 使用 PAT_TOKEN 確保有寫入權限
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git
          # 先拉取最新遠端更新，並使用 rebase 整合本地更改
          git pull --rebase origin main
          # 若有更新則加入、提交
          git add live_streams.txt
          git commit -m "Update YouTube live streams [skip ci]" || echo "No changes to commit"
          git push


