name: Update Live Streams

on:
  schedule:
    - cron: '0 */2 * * *'  # 每两小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库
        uses: actions/checkout@v2

      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install requests beautifulsoup4

      - name: 执行抓取脚本
        run: python your_script.py

      - name: 提交更新
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git pull --rebase  # 拉取最新的远程更改
          git add live_streams.txt
          git commit -m "更新直播列表" || echo "无更新内容"
          git push
