name: Update YouTube Live Streams

on:
  schedule:
    - cron: "0 */2 * * *"  # 每2小時執行
  workflow_dispatch:

jobs:
  update-live-streams:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出倉庫
        uses: actions/checkout@v3

      - name: 設定 Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: 安裝依賴
        run: pip install requests beautifulsoup4

      - name: 執行爬蟲
        run: python youtube_live_scraper.py

      - name: 設定 Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase  # 確保與遠端同步
          git add live_streams.txt
          git commit -m "更新 YouTube 直播鏈接 [skip ci]" || echo "沒有變化需要提交"
          git push
